---
# Java JDK Env Installation.
- include_tasks: java.yml
  tags:
  - java

# Pseudo-Distributed Hadoop Installation.
- include_tasks: install.yml
  tags:
  - install
#  when: not hadoop_installed.stat.exists
- include: configure.yml
  tags:
  - conf

